Issue #275:Update readme file, few improvements and also more highliht DOCKER usage as a way to speed up the environment process during set up.
ec-europa/atomium pull request #288
Opened 2019-03-21 13:11 UTC by aritomelo

Fix #275

2019-03-21 13:20 UTC, drupol commented on README.md
> +In order to get a render array, it requires a deeper analise and rewrite functions
s/analise/analyse ?

2019-03-21 15:28 UTC, drupol approved these changes
All good

2019-03-21 15:29 UTC, drupol requested changes

2019-03-21 15:29 UTC, drupol commented on README.md
> + The theme debug mode setting has been moved to registryonsteroids module.
Registry on steroids 
Also adding a link would be nice

2019-03-22 08:43 UTC, aritomelo commented
@drupol  is this tickets still needed work?

2019-03-22 08:45 UTC, drupol commented
@aritomelo It would be nice to use ` instead of * when referencing files or code, what do you think ?

2019-03-22 09:02 UTC, aritomelo commented
> @aritomelo It would be nice to use ` instead of * when referencing files or code, what do you think ?

An example pls? Thx

2019-03-22 09:04 UTC, drupol commented on README.md
> +  1. Copy `runner.yml.dist` into `runner.yml` and customize it according to your local environment
Here we are using `

2019-03-22 09:04 UTC, drupol commented on README.md
> +*atomium_drupal_get_breadcrumb()* is an Atomium internal function written only
Here we use *

2019-03-22 09:04 UTC, drupol commented
@aritomelo I commented

2019-03-22 09:12 UTC, aritomelo commented on README.md
> +  1. Copy `runner.yml.dist` into `runner.yml` and customize it according to your local environment
Well spot!

2019-03-22 11:00 UTC, drupol requested changes

2019-03-22 11:00 UTC, drupol commented on README.md
> +  2. Run `$ ./vendor/bin/run drupal:site-setup` which will setup site and tests configuration files, such as `phpunit.xml`
Remove the prepending $ please, it's easier to copy paste.

2019-03-22 11:00 UTC, drupol commented on README.md
> +  2. Install the site by running `$ ./vendor/bin/run drupal:site-install`
Remove the prepending $

2019-03-22 11:00 UTC, drupol commented on README.md
> +Theme definitions can be found in the *templates* directory of
Use ` instead of *

2019-03-22 11:00 UTC, drupol commented on README.md
> + - Create a directory in *templates* and name it as desired. A good practice
Use ` instead of *

2019-03-22 11:00 UTC, drupol commented on README.md
> +To add a component in there, A custom component needs to define two hooks:
"A custom" => the A should be lowercased.

2019-03-22 11:00 UTC, drupol commented on README.md
> +*atomium_drupal_get_breadcrumb()* is an Atomium internal function written only
Not fixed.

2019-03-22 11:21 UTC, aritomelo commented
@drupol Please, could you check line 185 .. 187 if they require changes?

Before the merge, I will squash this commit!

2019-03-22 12:20 UTC, drupol requested changes
Please, let's get this done today, let's not spend more than 2 days on this few lines changes.

2019-03-22 12:20 UTC, drupol commented on README.md
> +To enable the theme, go to *`admin/appearance`* and select
Please don't use *`, just one symbol only.

2019-03-22 12:20 UTC, drupol commented on README.md
> +As of Drupal 7.51, a new *`allow_css_double_underscores`* variable has been
Same here.

2019-03-22 12:20 UTC, drupol commented on README.md
> +Atomium provides a custom page available on the path: *`atomium-overview`*.
Same here.

2019-03-22 12:20 UTC, drupol commented on README.md
> +`template_process_page()` hook.
Good.

2019-03-22 12:20 UTC, drupol commented on README.md
> +The function `drupal_get_breadcrumb()` returns raw HTML.
Good

2019-03-22 12:20 UTC, drupol commented on README.md
> +`drupal_get_breadcrumb()` calls `menu_get_active_breadcrumb()`.
Good.

2019-03-22 12:20 UTC, drupol commented on README.md
> +This is why, in `page.tpl.php`, instead of writing:
Good.

2019-03-22 14:26 UTC, drupol requested changes

2019-03-22 14:26 UTC, drupol commented on README.md
> +  2. Run `$ ./vendor/bin/run drupal:site-setup` which will setup site and tests configuration files, such as `phpunit.xml`
```suggestion
  2. Run `./vendor/bin/run drupal:site-setup` which will setup site and tests configuration files, such as `phpunit.xml`
```

2019-03-22 14:26 UTC, drupol commented on README.md
> +  2. Install the site by running `$ ./vendor/bin/run drupal:site-install`
```suggestion
  2. Install the site by running `./vendor/bin/run drupal:site-install`
```

2019-03-22 14:31 UTC, drupol approved these changes

2019-03-22 14:44 UTC, merged