Issue #351: Update pager components enabling class attributes on links.
ec-europa/atomium pull request #352
Opened 2019-04-15 15:22 UTC by aritomelo

Fix #351

2019-04-15 17:07 UTC, drupol requested changes
:crying_cat_face:

2019-04-15 17:07 UTC, drupol commented on atomium/includes/common.inc
>  function atomium_find_templates() {
If `atomium_find_templates()` is not used elsewhere, please remove it completely then.

2019-04-15 17:07 UTC, drupol commented on atomium/includes/classes/Attributes.php
> -   * @deprecated
If the method is not used elsewhere, please remove it.

2019-04-16 08:27 UTC, drupol commented on docker-compose.yml
> +    - 8080
Why this ?

2019-04-16 08:29 UTC, aritomelo commented on docker-compose.yml
> +    - 8080
Mistake, only needed on my local!

2019-04-16 08:32 UTC, merged