#457 - Theme settings only override settings.php.
ec-europa/atomium pull request #458
Opened 2020-02-06 17:00 UTC by julien-

### Description

Now if `$theme_debug` or `$allow_css_double_underscores` is defined in _settings.php_ or s_ettings.local.php_ it will be taken in consideration.

2020-02-06 17:09 UTC, drupol requested changes
Small stuff to change before approving

2020-02-06 17:09 UTC, drupol commented on atomium/includes/config.inc
> + * Config file.
Unrelated changes.

2020-02-10 15:24 UTC, aritomelo commented on atomium/includes/config.inc
> + * Config file.
@drupol ++

2020-02-11 14:07 UTC, drupol commented
@julien- Could you update this PR so I can merge and tag release tonight ?

2020-02-11 14:11 UTC, julien- commented
@drupol It's Done
Thanks again

2020-02-11 14:12 UTC, merged